# Generated by Django 4.2.11 on 2024-05-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_involvement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('caption', models.CharField(max_length=1000)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('archive', models.BooleanField(default=False)),
                ('image_upload', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
