# Generated by Django 4.2.11 on 2024-05-28 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community_involvement', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('gcash_number', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('donated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_involvement.project')),
            ],
        ),
    ]
