# Generated by Django 4.2.11 on 2024-05-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_involvement', '0003_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='gcash_number',
            field=models.CharField(max_length=11),
        ),
    ]
