# Generated by Django 4.2.11 on 2024-05-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_involvement', '0004_alter_donation_gcash_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donated',
            field=models.CharField(max_length=255),
        ),
    ]
